language: ruby
rvm:
  - 1.9.3
  - 1.9.2
#  - jruby-19mode  # Fails to install sqlite3
  - rbx-19mode
#  - ruby-head    # Fails to download rubygems.org/latest_specs.4.8.gz
#  - jruby-head   # Fails to install sqlite3
bundler_args: "--binstubs --without documentation"
